//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace ProductInformationManager.Application.Resources;

using System.Resources;
using System.Globalization;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class ValidationMessages
{
    private static ResourceManager? _resourceManager;

    private static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "ProductInformationManager.Application.Resources.ValidationMessages",
            typeof(ValidationMessages).Assembly);

    private static CultureInfo? ResourceCulture { get; set; }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, ResourceCulture) ?? name;

    // -- Category --
    public static string CategoryNameRequired => GetString(nameof(CategoryNameRequired));
    public static string CategoryNameMaxLength => GetString(nameof(CategoryNameMaxLength));
    public static string CategoryNameDuplicate => GetString(nameof(CategoryNameDuplicate));
    public static string CategoryNotFound => GetString(nameof(CategoryNotFound));
    public static string CategoryDeleteHasChildren => GetString(nameof(CategoryDeleteHasChildren));
    public static string CategoryDeleteHasProducts => GetString(nameof(CategoryDeleteHasProducts));
    public static string CategoryDeleteHasDescriptions => GetString(nameof(CategoryDeleteHasDescriptions));
    public static string CategoryDescriptionMaxLength => GetString(nameof(CategoryDescriptionMaxLength));

    // -- DescriptionType --
    public static string DescriptionTypeNameRequired => GetString(nameof(DescriptionTypeNameRequired));
    public static string DescriptionTypeNameMaxLength => GetString(nameof(DescriptionTypeNameMaxLength));
    public static string DescriptionTypeNameDuplicate => GetString(nameof(DescriptionTypeNameDuplicate));
    public static string DescriptionTypeNotFound => GetString(nameof(DescriptionTypeNotFound));
    public static string DescriptionTypeDeleteInUse => GetString(nameof(DescriptionTypeDeleteInUse));
    public static string DescriptionTypeDescriptionMaxLength => GetString(nameof(DescriptionTypeDescriptionMaxLength));

    // -- DescriptionValue --
    public static string DescriptionValueRequired => GetString(nameof(DescriptionValueRequired));
    public static string DescriptionValueMaxLength => GetString(nameof(DescriptionValueMaxLength));
    public static string DescriptionValueDeleteInUse => GetString(nameof(DescriptionValueDeleteInUse));

    // -- AttributeType --
    public static string AttributeTypeNameRequired => GetString(nameof(AttributeTypeNameRequired));
    public static string AttributeTypeNameMaxLength => GetString(nameof(AttributeTypeNameMaxLength));
    public static string AttributeTypeNameDuplicate => GetString(nameof(AttributeTypeNameDuplicate));
    public static string AttributeTypeNotFound => GetString(nameof(AttributeTypeNotFound));
    public static string AttributeTypeDeleteInUse => GetString(nameof(AttributeTypeDeleteInUse));
    public static string AttributeTypeDescriptionMaxLength => GetString(nameof(AttributeTypeDescriptionMaxLength));

    // -- Attribute --
    public static string AttributeNameRequired => GetString(nameof(AttributeNameRequired));
    public static string AttributeValueRequired => GetString(nameof(AttributeValueRequired));
    public static string AttributeDeleteInUse => GetString(nameof(AttributeDeleteInUse));

    // -- Product --
    public static string ProductNameRequired => GetString(nameof(ProductNameRequired));
    public static string ProductNameMaxLength => GetString(nameof(ProductNameMaxLength));
    public static string ProductSkuRequired => GetString(nameof(ProductSkuRequired));
    public static string ProductSkuMaxLength => GetString(nameof(ProductSkuMaxLength));
    public static string ProductSkuDuplicate => GetString(nameof(ProductSkuDuplicate));
    public static string ProductCategoryRequired => GetString(nameof(ProductCategoryRequired));
    public static string ProductCategoryNotFound => GetString(nameof(ProductCategoryNotFound));
    public static string ProductNotFound => GetString(nameof(ProductNotFound));
    public static string ProductMandatoryDescriptionMissing => GetString(nameof(ProductMandatoryDescriptionMissing));

    // -- CategoryDescriptionRule --
    public static string CategoryDescriptionRuleAlreadyExists => GetString(nameof(CategoryDescriptionRuleAlreadyExists));
    public static string CategoryDescriptionRuleNotFound => GetString(nameof(CategoryDescriptionRuleNotFound));
    public static string CategoryDescriptionRuleDeleteInUse => GetString(nameof(CategoryDescriptionRuleDeleteInUse));
}
