// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductInformationManager.Infrastructure;

#nullable disable

namespace ProductInformationManager.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260410120000_AddIsGlobalToDescriptionTypes")]
    partial class AddIsGlobalToDescriptionTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductInformationManager.Domain.DescriptionType", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CreatedBy").HasColumnType("text");
                    b.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<bool>("IsGlobal").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("UpdatedBy").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("DescriptionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
